export default {
  login: "dishant0406",
  id: 90952604,
  node_id: "MDQ6VXNlcjkwOTUyNjA0",
  avatar_url: "https://avatars.githubusercontent.com/u/90952604?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/dishant0406",
  html_url: "https://github.com/dishant0406",
  followers_url: "https://api.github.com/users/dishant0406/followers",
  following_url: "https://api.github.com/users/dishant0406/following{/other_user}",
  gists_url: "https://api.github.com/users/dishant0406/gists{/gist_id}",
  starred_url: "https://api.github.com/users/dishant0406/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/dishant0406/subscriptions",
  organizations_url: "https://api.github.com/users/dishant0406/orgs",
  repos_url: "https://api.github.com/users/dishant0406/repos",
  events_url: "https://api.github.com/users/dishant0406/events{/privacy}",
  received_events_url: "https://api.github.com/users/dishant0406/received_events",
  type: "User",
  site_admin: false,
  name: "Dishant Sharma",
  company: null,
  blog: "https://dishantsharma.me",
  location: null,
  email: null,
  hireable: null,
  bio: "I am a web developer having expertise in frontend development and exposure to back- end development. I design and develop web applications using the latest technologies",
  twitter_username: "dishant0406",
  public_repos: 21,
  public_gists: 0,
  followers: 1,
  following: 2,
  created_at: "2021-09-18T06:05:52Z",
  updated_at: "2022-04-16T16:06:53Z"
};

// export default {
//   login: "john-smilga",
//   id: 42133389,
//   node_id: "MDQ6VXNlcjQyMTMzMzg5",
//   avatar_url: "https://avatars.githubusercontent.com/u/42133389?v=4",
//   gravatar_id: "",
//   url: "https://api.github.com/users/john-smilga",
//   html_url: "https://github.com/john-smilga",
//   followers_url: "https://api.github.com/users/john-smilga/followers",
//   following_url: "https://api.github.com/users/john-smilga/following{/other_user}",
//   gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
//   starred_url: "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
//   subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
//   organizations_url: "https://api.github.com/users/john-smilga/orgs",
//   repos_url: "https://api.github.com/users/john-smilga/repos",
//   events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
//   received_events_url: "https://api.github.com/users/john-smilga/received_events",
//   type: "User",
//   site_admin: false,
//   name: "John Smilga",
//   company: "Coding Addict",
//   blog: "www.johnsmilga.com",
//   location: "Los Angeles",
//   email: null,
//   hireable: null,
//   bio: "Creator of Coding Addict",
//   twitter_username: "john_smilga",
//   public_repos: 226,
//   public_gists: 0,
//   followers: 10083,
//   following: 0,
//   created_at: "2018-08-06T06:48:23Z",
//   updated_at: "2022-04-06T03:26:56Z"
// };